- resources/lang/en/urls.php
- resources/views/footer-social.blade.php
- src/UserInterfaceServiceProvider.php
> feat: lang loader & url langs

- resources/views/breadcrumbs.blade.php
- resources/views/navbar.blade.php
> refactor: add dark classes

- resources/tailwind.config.js
- resources/views/navbar.blade.php
> refactor: dark navbar

- resources/views/footer-bar-desktop.blade.php
> refactor: add footer bar class property

- resources/tailwind.config.js
> refactor: add max width tailwind option

- resources/views/inputs/toggle.blade.php
> refactor: toggle additions

- README.md
- resources/views/avatar.blade.php
- resources/views/navbar.blade.php
- src/UserInterfaceServiceProvider.php
> feat: avatar component

- resources/assets/css/_tables.css
> refactor: update table styling

- README.md
- resources/assets/js/page-scroll.js
- src/Http/Livewire/Concerns/HasPagination.php
> feat: pagination scroll top

- resources/assets/css/_buttons.css
- resources/assets/css/_tables.css
> refactor: dark mode tweaks

- resources/assets/css/_tables.css
- resources/views/dropdown.blade.php
> refactor: table & dropdown dark mode tweaks

- README.md
- resources/assets/css/_general.css
> refactor: dark mode headings & tippy docs

- resources/assets/css/_general.css
> fix: responsive font sizes

- resources/assets/css/_general.css
> fix: inconsistent header sizes

- README.md
- resources/assets/css/_general.css
- resources/assets/js/picasso.ts
> refactor: extract picasso package

- resources/assets/js/picasso.ts
> fix: picasso avatar background

- resources/views/dropdown.blade.php
> refactor: dropdown component custom property

- resources/assets/css/_buttons.css
- resources/assets/css/_components.css
- resources/assets/css/_forms.css
> refactor: dark mode style guide changes

- resources/assets/css/_components.css
> refactor: add selected dropdown class

- resources/assets/css/_forms.css
- resources/views/inputs/toggle.blade.php
> refactor: input toggle dark mode

- resources/views/footer-copyright.blade.php
> refactor: footer wrapping on small devices

- resources/assets/css/_components.css
> refactor: dropdown scrollbar css

- EXAMPLES.md
- resources/views/icon.blade.php
- src/UserInterfaceServiceProvider.php
> feat: icon component

- resources/views/inputs/rich-select.blade.php
Now that this PR was merged https://github.com/ArkEcosystem/laravel-ui/pull/48 the only missing thing was to update the icon name to make it work
> fix: use library icon

- resources/assets/icons/user-team.svg
> chore: update user team icon

- resources/assets/icons/brands/telegram.svg
- resources/lang/en/urls.php
- resources/views/footer-bar-mobile.blade.php
- resources/views/footer-social.blade.php
> refactor: add footer telegram icon

- resources/assets/css/_components.css
- resources/tailwind.config.js
- resources/views/ark-navbar-link-mobile.blade.php
- resources/views/modal.blade.php
- src/UserInterfaceServiceProvider.php
> refactor: dark mode & navbar tweaks

- resources/views/modal.blade.php
> refactor: custom modal scrollbar

- src/Support/DateFormat.php
> refactor: short time date format

- resources/assets/icons/menu-show.svg
- resources/assets/icons/menu.svg
- resources/assets/icons/search.svg
- resources/views/navbar.blade.php
> chore: menu & search icon updates

- resources/assets/css/_components.css
> fix: navbar current page style

- resources/assets/css/_components.css
- resources/views/inputs/rich-select.blade.php
> refactor: dropdown entry style consistency

- resources/assets/css/_components.css
- resources/views/inputs/rich-select.blade.php
> refactor: dropdown use medium font

- resources/views/inputs/input-with-icon.blade.php
- resources/views/inputs/input.blade.php
> refactor: add pattern and inputmode attributes on input component

- resources/views/footer-bar-desktop.blade.php
- resources/views/footer.blade.php
- resources/views/metatags.blade.php
- src/UserInterfaceServiceProvider.php
> refactor: add footer & metatag components

- resources/tailwind.config.js
> chore: add border widths

- resources/views/pagination-url.blade.php
- resources/views/pagination.blade.php
Make use of `<x-icon />` instead of `@svg`
> refactor: use icon component for pagination

- resources/assets/css/_tables.css
- resources/views/tables/cell.blade.php
- resources/views/tables/row.blade.php
- src/UserInterfaceServiceProvider.php
- Add a few CSS classes for the hover & highlight effects for the tables
- Adds a new `<x-ark-tables.cell />` component that should be used instead of the  table `<td />`, this component adds an extra div and a couple of classes that helps to create the table hover effect.
- Adds a new  `<x-ark-tables.row />` component that accepts the `:warning` and `:danger` , when  they have truthy values it highlights the cell accordingly
### Note
The cell component has the `firstOn` and `lastOn` props, those only need to be defined if the specified cell column is the last one (or the first one) only in certain screen sizes, and helps to create the rounded border that depends on CSS pseudo selector that doesn't works if the last (or first) cell is hidden
Example:
```
@foreach($transactions as …
```
> feat: hover & highlight effects for the table cells and related components

- resources/assets/css/_tables.css
- resources/tailwind.config.js
- resources/views/footer-bar-desktop.blade.php
- resources/views/tables/cell.blade.php
- Fixs the broken hover effect on safari browsers
- Refactor the cell component for better integration with purgecss
- Remove deprecated whitelist setting on purgecss
> fix: buggy hover effect on safari

- resources/views/footer-bar-mobile.blade.php
> refactor: remove mobile footer margin

- resources/assets/css/styles-with-prism.css
- resources/assets/css/styles.css
https://app.clickup.com/t/a8xda1
> refactor: add bulk import css files

- resources/assets/css/_tables.css
- resources/views/tables/cell.blade.php
> fix: table cell right alignment

- resources/views/inputs/input-with-icon.blade.php
- resources/views/inputs/input.blade.php
- tests/Helpers.php
- tests/Views/Inputs/InputTest.php
- tests/Views/Inputs/InputWithIconTest.php
> refactor: have inputs make use of attributes bag

- resources/views/inputs/input-with-icon.blade.php
- resources/views/inputs/input.blade.php
> fix: input attribute exclusions

- resources/assets/css/_tables.css
> fix: table row hover padding

- resources/views/breadcrumbs.blade.php
> refactor: remove breadcrumb class options

- resources/tailwind.config.js
> refactor: exclude fortify views from purge

- resources/assets/css/_components.css
- resources/assets/icons/vertical-dots.svg
- resources/views/details-box-mobile.blade.php
- resources/views/details-box.blade.php
- resources/views/status-circle-shallow.blade.php
- src/UserInterfaceServiceProvider.php
> refactor: additional components & update vertical icon

- resources/views/dropdown.blade.php
- resources/views/status-circle-shallow.blade.php
> refactor: component tweaks

- resources/views/tables/header.blade.php
- resources/views/tables/view-options.blade.php
- src/UserInterfaceServiceProvider.php
> feat: table components

- resources/views/tables/view-options.blade.php
> refactor: table view options mobile property

- resources/assets/css/_tables.css
> fix: table last column no border

- resources/assets/css/_tables.css
- resources/views/tables/header.blade.php
> refactor: update full width table header border

- resources/tailwind.config.js
> refactor: exclude hermes views from purge

- resources/assets/js/reposition-dropdown.js
- resources/views/dropdown.blade.php
> feat: dropdown reposition on bottom overflow

- resources/lang/en/status.php
> chore: add error status lang

- resources/views/inputs/rich-select.blade.php
New slots on the rich select that allows us to create custom views for the options list and the selected options
Used here https://github.com/ArkEcosystem/nodem/pull/54
> feat: rich select allow custom list and custom selected option text

- resources/views/inputs/rich-select.blade.php
- Fixes an issue when handling initial value when the select is rendered again
- Related to this error https://github.com/ArkEcosystem/nodem/pull/54#issuecomment-733168429
- While testing that this doesnt broke explorer I found a bug and noticed that some of the logic added there was unnecessary so I remove some code (the bug will be fixed on the explorer branch)
Tested in both explorer and nodem projects*
> fix: rich select initial value handling

- resources/views/dropdown.blade.php
- resources/views/navbar/items/desktop.blade.php
- resources/views/sidebar-link.blade.php
> chore: dusk attributes in navbar for easing testing

- README.md
- resources/assets/css/_pikaday.css
- resources/views/inputs/date-picker.blade.php
- src/UserInterfaceServiceProvider.php
> feat: date picker component

- resources/views/navbar/profile.blade.php
> chore: dusk attributes in profile dropdown for easing testing

- resources/assets/css/_general.css
- resources/assets/css/_tables.css
> fix: table header border positions

- resources/assets/css/_components.css
- resources/views/inputs/rich-select.blade.php
- resources/views/inputs/time.blade.php
- resources/views/modal.blade.php
Misc UI changes necessary to update the filter form on nodem.
https://app.clickup.com/t/auvcrx
The time inputs use the dropdown component to list the time's options, this is slightly different from the dropdown on the style guide and also doesn't have a few handly UX stuff like arrow navigation that the current `rich-dropdown` component has.
So I updated the time input to use the dropdown component behind the scenes, now it looks like this:
Since the modal has an overflow if I show the dropdown list we have this issue:
What I do was to optionally add the overflow, that may be an issue if the modal is long but in this case is not a problem.
The alternatives were:
1. to use JS to add the dropdown list outside of the component DOM and position it with JS, that is tricky and require some …
> feat: misc ui changes for the filter form on nodem

- resources/assets/css/_general.css
> style: remove tailwind class prefixes

- resources/assets/css/styles.css
- resources/assets/css/third-party/tailwindcss-custom-forms.css
> refactor: copy tailwind forms css

- resources/assets/css/_buttons.css
- resources/assets/css/_components.css
- resources/assets/css/_forms.css
- resources/assets/css/_general.css
- resources/assets/css/_tables.css
- resources/tailwind.config.js
> chore: add dark mode tailwind config

- resources/tailwind.config.js
> chore: tippy purge safelist

- resources/assets/css/third-party/tailwindcss-custom-forms.css
> refactor: remove input shadows

- resources/assets/css/_forms.css
> fix: input padding override

- resources/views/inputs/rich-select.blade.php
> fix: typo on rich select component

- composer.json
- composer.lock
> chore: allow php 8 as a platform requirement

- resources/assets/css/_document.css
> feat: anchor navbar scroll offset

- resources/assets/js/modal.js
- resources/views/modal.blade.php
On deployer, we have a div that has a child modal that uses some alpine data, this data was conflicting with the div data, so this PR changes the modal script to merge some custom data with the modal data.
see https://github.com/ArkEcosystem/deployer.io/pull/925/files#diff-452311050cc50df6553049d0eb8fb5913f62ee804c7eb7d7e5d75dc08a726276R9
> feat: allow to merge more alpine data to the modal

- resources/views/info.blade.php
- resources/views/slider.blade.php
> refactor: slider title tooltip & additional content property

- resources/lang/en/urls.php
Add some Urls needed on the marketsquare footer (https://github.com/ArkEcosystem/marketsquare.io/pull/1001)
> feat: add urls needed for the msq footer

- resources/assets/css/_forms.css
- resources/views/inputs/rich-select.blade.php
> refactor: rich select component updates

- resources/lang/en/urls.php
- resources/views/pages/contact/content.blade.php
> refactor: allow contact page discord override

- resources/views/details-box.blade.php
> refactor: remove spacing on details box

- resources/views/inputs/rich-select.blade.php
> fix: rich select width

- resources/tailwind.config.js
> chore: tailwind add pika to purge safelist

- resources/views/sort-icon.blade.php
- src/UserInterfaceServiceProvider.php
> feat: sort icon component

- resources/lang/en/forms.php
- resources/views/inputs/markdown.blade.php
- src/Casts/Markdown.php
- src/UserInterfaceServiceProvider.php
For now, is just a wrapper for the textarea component, still think is a good idea to separate this component.
1. It has a text that says that the user can use github flavored
2. If we add more styling, preview mode, and future features we can just update that component
3. I am adding a markdown caster that should be used to prevent XSS injection
> feat: markdown component

- resources/views/slider.blade.php
> fix: mobile slider breakpoints

- resources/views/slider.blade.php
> fix: slider breakpoint encoding

- resources/assets/icons/send-email.svg
> chore: add send email icon

- resources/assets/css/_slider.css
- resources/views/slider.blade.php
> refactor: slider title & pagination positioning

- resources/views/details-box.blade.php
> refactor: details box props & allow class

- resources/assets/css/_general.css
> refactor: headers spacing

- resources/assets/css/_document.css
> refactor: update image caption style

- resources/assets/icons/checkmark-thin.svg
- resources/assets/icons/download.svg
> chore: icon changes

- resources/views/navbar/items/desktop.blade.php
- tests/Views/NavbarTest.php
- tests/Views/Navigation/Items/DesktopTest.php
> refactor: navbar breakpoint property

- resources/assets/css/_general.css
> refactor: copy content container css

- resources/views/container.blade.php
- src/UserInterfaceServiceProvider.php
> feat: container component

- resources/views/navbar.blade.php
- resources/views/navbar/hamburger.blade.php
- resources/views/navbar/items/desktop.blade.php
- resources/views/navbar/items/mobile.blade.php
- tests/Views/Navigation/Dropdown/ProfileTest.php
- tests/Views/Navigation/HamburgerTest.php
- tests/Views/Navigation/Items/MobileTest.php
- tests/Views/Navigation/LogoTest.php
Also fixes a small unnoticed bug whereby opening the dropdown menu then going to a larger display resulted in the backdrop still being shown but no dropdown.
> refactor: navbar breakpoint changes

- README.md
> chore: update publish command for clipboard example

- resources/views/tables/mobile/cell.blade.php
- resources/views/tables/mobile/row.blade.php
- src/UserInterfaceServiceProvider.php
> feat: mobile table components

- resources/assets/css/_tables.css
- resources/views/tables/mobile/row.blade.php
> refactor: add mobile table css

- resources/views/navbar/profile.blade.php
https://app.clickup.com/t/c4u63q
> fix: avatar dropdown arrow rotation

- resources/views/modal.blade.php
> refactor: increase modal padding

- resources/views/inputs/checkbox.blade.php
> refactor: checkbox component

- resources/assets/css/_alerts.css
- resources/views/alert.blade.php
> refactor: added break-all to the message of the alert

- EXAMPLES.md
- resources/assets/css/_components.css
- resources/assets/css/_forms.css
- resources/lang/en/general.php
- resources/views/inputs/tile-selection-option.blade.php
- resources/views/inputs/tile-selection.blade.php
- src/UserInterfaceServiceProvider.php
> feat: tile selection component

- resources/assets/css/_forms.css
- resources/views/inputs/includes/input-field.blade.php
- resources/views/inputs/includes/input-internal-icon.blade.php
- resources/views/inputs/includes/input-label.blade.php
- resources/views/inputs/input-error.blade.php
- resources/views/inputs/input-with-icon.blade.php
- resources/views/inputs/input-with-prefix.blade.php
- resources/views/inputs/input.blade.php
- src/UserInterfaceServiceProvider.php
- tests/Views/Inputs/InputWithPrefixTest.php
> feat: input with prefix component

- resources/assets/js/tippy.js
> refactor: add tippy hover selector

- resources/views/slider.blade.php
Autoplay option needed for the home slider
> feat: add autoplay prop and hide bullets on slider for msq home slider

- resources/assets/css/_components.css
- resources/views/inputs/tile-selection-option.blade.php
- resources/views/inputs/tile-selection.blade.php
> refactor: tile selection updates

- EXAMPLES.md
- resources/assets/css/_components.css
- resources/views/inputs/tile-selection-option.blade.php
- resources/views/inputs/tile-selection.blade.php
> refactor: allow tile selection as single option/radio buttons

- README.md
- src/UserInterfaceServiceProvider.php
Also, update the readme considering that the projects will have an alias `@ui` like the one I added on msq, I can add that alias when I update the different project's assets.
With the JS tag I left only the assets that are not mentioned on the README and I am not sure how they are used.
> feat: no need to publish all the scripts within the JS tag

- resources/views/slider.blade.php
Adds a new slot to the slider component and a way to modify some classes needed for the network hub slider on msq home page
> feat: slot to add a custom button after the navigation

- resources/assets/css/_components.css
- resources/lang/en/forms.php
- resources/views/inputs/upload-image-collection.blade.php
- src/Components/UploadImageCollection.php
- src/UserInterfaceServiceProvider.php
> feat: upload image collection component

- src/Components/UploadImageCollection.php
- src/Components/UploadImageSingle.php
- Also reverts back to validators method instead of property
> refactor: upload component - readd readonly property & use validators method

- resources/views/inputs/includes/input-label.blade.php
- resources/views/inputs/input-with-icon.blade.php
- resources/views/inputs/input-with-prefix.blade.php
- resources/views/inputs/input.blade.php
- resources/views/inputs/markdown.blade.php
- resources/views/inputs/tile-selection.blade.php
- src/Components/UploadImageCollection.php
> refactor: input & tile component tweaks

- resources/assets/js/page-scroll.js
- resources/views/container.blade.php
- resources/views/inputs/upload-image-collection.blade.php
- src/Components/UploadImageCollection.php
> refactor: project registration form tweaks

- resources/assets/css/_components.css
- resources/views/inputs/tile-selection-option.blade.php
- resources/views/inputs/tile-selection.blade.php
> refactor: hide tile options on mobile with show more

- resources/assets/css/_components.css
- resources/lang/en/general.php
> refactor: tile selection tweaks

- resources/views/inputs/input-with-prefix.blade.php
> refactor: input with prefix dirty check

- resources/views/inputs/upload-image-single.blade.php
Emit an event on upload error.
> feat: emit event on upload error

- resources/views/accordion.blade.php
> refactor: accordion component changes

- resources/views/pages/contact/content.blade.php
- resources/views/pages/contact/header.blade.php
draft; waiting on some header questions
> refactor: contact page

- resources/views/dropdown.blade.php
Related to https://app.clickup.com/t/d91e1x
> refactor: make button class overridable

- resources/views/navbar/profile.blade.php
Now when hovered the avatar will have the blue border
> chore: add hover state to the navbar avatar

- resources/lang/en/general.php
> chore: add hide to langs

- resources/views/icon.blade.php
> fix: icon component size

- resources/assets/icons/messages.svg
Needed for the messages link on the navbar
> chore: navbar messages icon

- resources/assets/css/_slider.css
- resources/views/slider.blade.php
https://app.clickup.com/t/devzd4
> refactor: slider design pagination

- resources/views/slider.blade.php
> refactor: slider responsive top pagination

- resources/views/inputs/checkbox.blade.php
> refactor: checkbox position class

- resources/assets/css/_components.css
- resources/assets/css/_slider.css
> refactor: tile selection & slider styles

- resources/assets/css/_components.css
- resources/assets/js/navbar.js
- resources/views/navbar.blade.php
Also includes navbar scrolling change to prevent scroll change when the dropdown is open (like modals)
> refactor: tile links style, move navbar js

- resources/assets/css/_components.css
> refactor: dropdown entry class tweaks

- resources/views/alert.blade.php
> refactor: font size tweaks for alert component

- resources/assets/css/_components.css
> refactor: tile link with transition & no border

- resources/views/inputs/includes/tile-selection-option.blade.php
- resources/views/inputs/tile-selection-option.blade.php
- resources/views/inputs/tile-selection.blade.php
More options for better customization when using the component.
> refactor: selection tiles tweaks

- resources/assets/js/tippy.js
https://app.clickup.com/t/e92d05
> refactor: tooltip duration

- resources/assets/css/_components.css
- resources/views/inputs/includes/tile-selection-option.blade.php
- resources/views/inputs/tile-selection.blade.php
> refactor: tile selection properties

- resources/views/container.blade.php
https://app.clickup.com/t/eayt25
> refactor: container

- resources/assets/css/_components.css
https://app.clickup.com/t/ecy9x4
> fix: tile link show more css

- resources/assets/css/_components.css
- resources/assets/js/file-download.js
- resources/lang/en/actions.php
- resources/views/file-download.blade.php
- src/UserInterfaceServiceProvider.php
> feat: file download component

- resources/views/file-download.blade.php
- src/UserInterfaceServiceProvider.php
> fix: register file-download into package service provider

- resources/assets/css/_forms.css
- resources/assets/js/tags.js
- resources/views/inputs/tags.blade.php
Solves some alignment problems on the tags component, move the styles related to the component to this package and adds the possibility of setting a placeholder
> chore: tags component design tweaks

- README.md
- src/Providers/FormatReadTimeServiceProvider.php
- src/helpers.php
> refactor: read time helper

- resources/views/alert.blade.php
> refactor: make default alert font size sm

- resources/lang/en/actions.php
- resources/views/accordion.blade.php
> refactor: accordion component toggling tweaks

- resources/views/accordion.blade.php
> fix: use cloak for toggle title

- resources/views/inputs/textarea.blade.php
> refactor: update textarea label include

- resources/assets/icons/shield.svg
Icon used on msq to mark verified projects
> chore: add shield icon

- resources/views/inputs/textarea.blade.php
> refactor: textarea maxlength property

- resources/assets/css/_buttons.css
> refactor: update secondary button style

- EXAMPLES.md
- README.md
- resources/views/dropdown.blade.php
https://app.clickup.com/t/en05f5
> feat: add full-screen property to dropdown component

- .github/PULL_REQUEST_TEMPLATE.md
- resources/assets/js/tags.js
- resources/views/inputs/includes/input-error-tooltip.blade.php
- resources/views/inputs/tags.blade.php
> fix: tag input error tooltip

- resources/assets/css/_alerts.css
- resources/views/alert.blade.php
> refactor: tweak alerts to match new design

- resources/assets/css/_expandable.css
> fix: fix issue when minifying `_expandable.css`

- EXAMPLES.md
- README.md
- resources/views/expandable.blade.php
-   [x] Documentation _(if necessary)_
> chore: improve expandable component

- resources/assets/css/_forms.css
- resources/views/inputs/tags.blade.php
> refactor: disabled tags input style tweaks

- resources/views/inputs/includes/tile-selection-option.blade.php
> fix: disabled tile tooltip

- resources/views/inputs/tags.blade.php
> refactor: tooltip on the tags component if disabled

- src/Components/Concerns/HandleUploadError.php
- src/Components/UploadImageCollection.php
- src/Components/UploadImageSingle.php
> fix: reset error bag after displaying upload error

- resources/views/navbar/notifications.blade.php
https://app.clickup.com/t/f92tdr
> fix: reduce border radius on notification dropdown

- src/Casts/Markdown.php
https://app.clickup.com/t/f33ztu
The current implementation of the markdown caster is encoding the HTML entities to prevent XSS issues, which is causing issues with encoded characters like `...` (as the example in the ticket) and other chars like accents `Á` and in general, every character that is subject to be encoded since they are shown encoded when editing the value.
This PR removes the `htmlentities` method, so the chars are not being encoded anymore, and the problem is solved.
Still, some regards:
- Even though I could not find any XSS vulnerability, the casting method is theoretically less safe than it used to be.
- I'm proposing this fix considering the (theoretical) decrease of security because still there is a pending ticket related to XSS issues with the markdown where we can …
> fix: rollback html entities when editing

- resources/views/external-link.blade.php
Was originally related to https://app.clickup.com/t/f34146 but changes ended up not being necessary. Kept the PR open as it tidies the component up a little
> refactor: external url component props

- resources/views/inputs/upload-image-collection.blade.php
- src/Components/Concerns/HandleUploadError.php
- src/Components/UploadImageCollection.php
+ The upload component now allows the user to upload multiple images at a time
+ Plus, the functionality to "drop an image" was not working. This PR also fixes that
Upgrade this library msq (once merged) and go to create/edit a project, try to select multiple images to upload in the part of the images, you should be able to upload more than one image at a time
-   [] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_ …
> feat: allow to upload multiple files at time on upload images component

- resources/assets/css/_components.css
- resources/views/modal.blade.php
Slight tweaks to fit the latest design changes for modals.
> refactor: modal padding tweak

- resources/assets/css/_slider.css
> refactor: slider bottom padding

- resources/assets/css/_slider.css
Reverts ArkEcosystem/laravel-ui#356
> fix: revert slider bottom padding

- resources/assets/js/user-tagger.js
https://app.clickup.com/t/fn6g8f
> refactor: allow to tag user through name or display name

- resources/assets/js/markdown-editor/css/style.css
- resources/assets/js/markdown-editor/markdown-editor.js
- resources/assets/js/markdown-editor/plugins/alert.js
- resources/assets/js/markdown-editor/plugins/preview.js
- resources/assets/js/markdown-editor/plugins/reference.js
- resources/assets/js/markdown-editor/plugins/underline.js
PR https://app.clickup.com/t/en5dt2
Changes for making the markdown editor more friendly in mobile
You can test it by upgrading to this version of the package on msq and temporary changing to toolbar="full" (to see all buttons) on the `resources/views/livewire/update-profile.blade.php`:
```
<x-ark-markdown
name="about"
toolbar="full"
height="350px"
:chars-limit="1000"
hide-label
:show-reading-time="false"
/>
```
Then go to edit profile, you should see the full editor, use devtools to see responsive versions.
1. The design is adding line numbers on the preview, there is no easy way to implement this without patching the library behind the preview
2. The preview has numbers for the code blocks, even harder to implement 
3. The preview has the `documentation-content ` class and the style is …
> feat: responsive markdown design

- resources/assets/js/markdown-editor/plugins/twitter.js
https://app.clickup.com/t/fq25kq
> refactor: twitter id wording

- resources/views/metatags.blade.php
> refactor: metatags trim image

- resources/assets/css/_forms.css
- resources/views/inputs/includes/input-field.blade.php
https://app.clickup.com/t/g18ab3
> refactor: input field tweaks

- resources/assets/css/_general.css
https://app.clickup.com/t/g354mc
> refactor: responsive text css helper

- resources/views/inputs/includes/tile-selection-option.blade.php
Reverts ArkEcosystem/laravel-ui#370
Regarding to the comments on this ticket https://app.clickup.com/t/g32f3z
Im going to use an alternative solution that will be added directly on msq
> revert: "fix: disable tile selection while making requests"

- src/Components/UploadImageCollection.php
- src/Components/UploadImageSingle.php
This is currently set to min 148x148 and not configurable yet
> feat: add minimum dimensions to image upload

- resources/views/inputs/tags.blade.php
https://app.clickup.com/t/g71ftu
> fix: tags disabled tooltip

- README.md
> chore: update readme with correct markdown editor copy command

- README.md
> chore: adjust markdown editor setup steps

- EXAMPLES.md
- README.md
- resources/assets/css/_fonts.css
- resources/views/font-loader.blade.php
- src/UserInterfaceServiceProvider.php
- tests/Helpers.php
- tests/Views/FontLoaderTest.php
Related to: https://github.com/ArkEcosystem/marketsquare.io/pull/1589
-   [x] Documentation _(if necessary)_
> perf: add font loader component

- resources/views/dropdown.blade.php
- resources/views/navbar/profile.blade.php
Relates to https://app.clickup.com/t/qk4vwv
Updated margin and padding for the profile navbar dropdown
New implementation:
Design:
> refactor: update profile dropdown margin

- resources/assets/js/tags.js
https://app.clickup.com/t/qn6mc2
> refactor: tags case insensitive

- resources/views/inputs/includes/tile-selection-option.blade.php
- https://app.clickup.com/t/fn64em
- https://github.com/ArkEcosystem/marketsquare.io/pull/1516
> refactor: improve dusk discoverability and accessibility

- resources/views/inputs/includes/input-field.blade.php
- tests/Views/Inputs/InputTest.php
https://github.com/ArkEcosystem/laravel-fortify/pull/107#pullrequestreview-623140363
> feat: add input field `autocapitalize` attribute

- resources/assets/css/_alerts.css
- resources/views/alert.blade.php
Stemmed from https://app.clickup.com/t/fz77yu although not required in the end
> refactor: alert component

- resources/lang/en/general.php
- resources/views/navbar/profile.blade.php
https://app.clickup.com/t/gd5a42
> fix: remove double border on custom profile picture

- resources/views/dropdown.blade.php
- resources/views/expandable.blade.php
https://app.clickup.com/t/g986cq
> refactor: check image onload is set

- resources/views/pages/contact/content.blade.php
> refactor: add contact page props for content

- resources/lang/en/general.php
- resources/views/no-results.blade.php
https://app.clickup.com/t/qk5n32
> refactor: default no results text

- resources/assets/css/_buttons.css
https://app.clickup.com/t/gb2tp8
> fix: tags button text-alignment on mobile

- src/Rules/Concerns/ValidatesMarkdown.php
- src/Rules/MarkdownWithContent.php
- tests/Rules/MarkdownWithContentTest.php
related to https://app.clickup.com/t/g97nfg
New validation rule for non-empty markdown content, including zero width space characters
-   [x I provided a screenshot of my changes to the component _(if applicable)_
> feat: markdown with content validator

- resources/views/inputs/upload-image-collection.blade.php
https://app.clickup.com/t/gb0122
> fix: upload image collection click container

- resources/views/inputs/includes/input-label.blade.php
- resources/views/inputs/input-with-icon.blade.php
- resources/views/inputs/input-with-prefix.blade.php
- resources/views/inputs/input.blade.php
- resources/views/inputs/textarea.blade.php
related to https://github.com/ArkEcosystem/laravel-fortify/pull/122
> feat: add auxiliary title to text input

- resources/assets/css/_buttons.css
- resources/assets/css/_forms.css
https://app.clickup.com/t/qn6m4k
> fix: add word-break on tags

- resources/assets/css/_components.css
- resources/tailwind.config.js
Waiting on https://github.com/ArkEcosystem/laravel-ui/pull/426 to remove `xl`
https://app.clickup.com/t/h38jwb
> refactor: update modal border radius

- resources/views/navbar/notifications.blade.php
> refactor: additional dusk selectors for notifications

- resources/assets/css/_forms.css
- resources/views/inputs/input-with-prefix.blade.php
- resources/views/inputs/input.blade.php
https://app.clickup.com/t/gb05ad
> refactor: update prefix input component

- resources/assets/css/_forms.css
https://app.clickup.com/t/gb0u3q
> fix: remove unwanted expands/wraps on input tags

- resources/assets/css/_forms.css
- resources/views/inputs/includes/input-prefix-icon.blade.php
- resources/views/inputs/input-with-prefix.blade.php
https://app.clickup.com/t/gb05ad
> fix: input icon style

- resources/views/inputs/includes/input-field.blade.php
- resources/views/inputs/input-with-prefix.blade.php
https://app.clickup.com/t/gb05ad
> fix: input prefix error styling

- resources/assets/css/_alerts.css
- resources/assets/css/_components.css
- resources/assets/css/_document.css
- resources/assets/css/_forms.css
- resources/assets/css/_general.css
- resources/assets/css/_markdown-editor.css
- resources/assets/css/_tables.css
- resources/assets/css/_toasts.css
- resources/assets/js/markdown-editor/plugins/embed-link.js
- resources/assets/js/markdown-editor/plugins/reference.js
- resources/views/accordion-group.blade.php
- resources/views/accordion.blade.php
- resources/views/avatar.blade.php
- resources/views/code-lines.blade.php
- resources/views/code.blade.php
- resources/views/errors/error.blade.php
- resources/views/external-link-confirm.blade.php
- resources/views/navbar/notifications.blade.php
- resources/views/navbar/profile.blade.php
- resources/views/secondary-menu.blade.php
- resources/views/shapes/line.blade.php
- resources/views/shapes/square.blade.php
- resources/views/sidebar-link.blade.php
- resources/views/social-square.blade.php
https://app.clickup.com/t/h96exw
> refactor: change border radius

- resources/views/navbar/profile.blade.php
> fix: avatar border radius

- resources/views/navbar/profile.blade.php
https://app.clickup.com/t/hb6qkb
> refactor: full width mobile profile dropdown

- resources/views/navbar/profile.blade.php
https://app.clickup.com/t/hb6fwz
> refactor: update navbar profile radiuses & spacing

- resources/assets/css/_components.css
https://app.clickup.com/t/hd7xa5
> refactor: tile selector border radius

- resources/assets/js/navbar.js
- resources/views/navbar.blade.php
https://app.clickup.com/t/qk8964
Misc changes to the navbar script and dropdown markdown to make prevent buggy scrolling on ios
Needed to be merge within the msq related PR
> fix: broken scroll on navbar dropdown on mobile

- resources/assets/js/tags.js
https://app.clickup.com/t/hb8e0v
> fix: input tag disable toggling

- resources/assets/js/markdown-editor/markdown-editor.js
Related to https://app.clickup.com/t/hvb274
> fix: trim whitespace before counting in editor

- resources/assets/css/_forms.css
- resources/views/inputs/select.blade.php
> fix: replace `shadow-outline` with `ring`

- resources/assets/js/tags.js
- resources/lang/en/validation.php
- src/Rules/Tag.php
- src/Support/Enums/Constants.php
- tests/Rules/TagTest.php
https://app.clickup.com/t/j12uh4
> refactor: allow spaces and hyphens in tags

- resources/views/navbar.blade.php
- resources/views/slider.blade.php
https://app.clickup.com/t/jnav2b
Adjustments to sliders and navbar margins to match the new container's margins.
> refactor: adjust margins to match the new containers

- src/Rules/Concerns/ValidatesMarkdown.php
- tests/Rules/MarkdownMaxCharsTest.php
https://app.clickup.com/t/jkbxbm
> refactor: update markdown char count validator

- resources/assets/js/read-more.js
- resources/views/read-more.blade.php
- src/UserInterfaceServiceProvider.php
https://app.clickup.com/t/jd8c5x
> feat: read more component

- resources/views/logo-simple.blade.php
Needed for adding a class on the ark website for this PR https://github.com/ArkEcosystem/ark.io/pull/950/files
> refactor: accept link class option on logo component

- resources/assets/css/_general.css
This is needed to make the change in https://github.com/ArkEcosystem/laravel-ui/pull/464 work properly, otherwise the media queries are ignored
> refactor: rewrite content-container style so it can be included in css

- resources/lang/en/actions.php
- resources/views/read-more.blade.php
> refactor: read more tweaks

- resources/views/tables/table.blade.php
- src/UserInterfaceServiceProvider.php
Tabla component with `sticky` setting and that by default already contains the table container that usually is also needed.
Related to https://github.com/ArkEcosystem/explorer.ark.io/pull/703
-   [ ] …
> feat: table + table container component

- resources/assets/css/_tables.css
- resources/tailwind.config.js
https://app.clickup.com/t/kdbhej
It still looks a little odd with the filter open above the columns while scrolled down
> refactor: update sticky column overlap

- resources/assets/css/_components.css
https://app.clickup.com/t/kfd1kd
> refactor: update tab height

- resources/assets/css/_components.css
https://app.clickup.com/t/kh9qbr
Some classes the were added to explorer but belongs to here
> chore: move dropdown classes adjustments from explorer

- resources/assets/js/crop-image.js
> fix: reset upload input after failing validation

- resources/assets/js/utils.js
- resources/views/inputs/upload-image-single.blade.php
> chore: change image validator error messages

- resources/assets/css/_buttons.css
https://app.clickup.com/t/kz51ea
Updating the CSS for preventing the shift 
> fix: shift when hovering ellipsis in pagination

- resources/assets/css/_components.css
- resources/views/accordion-group.blade.php
- resources/views/breadcrumbs.blade.php
- resources/views/errors/error.blade.php
- resources/views/inputs/rich-select.blade.php
- resources/views/inputs/tile-selection.blade.php
- resources/views/inputs/toggle.blade.php
- resources/views/inputs/upload-image-single.blade.php
- resources/views/js-modal.blade.php
- resources/views/link-collection.blade.php
- resources/views/modal.blade.php
- resources/views/navbar.blade.php
- resources/views/navbar/content.blade.php
- resources/views/navbar/hamburger.blade.php
- resources/views/navbar/items/mobile.blade.php
- resources/views/navbar/profile.blade.php
- resources/views/pages/contact/content.blade.php
- resources/views/pagination-url.blade.php
- resources/views/pagination.blade.php
> refactor: update dropdown styling

- resources/assets/css/_components.css
> refactor: dropdown entry nowrap

- resources/views/external-link-confirm.blade.php
https://app.clickup.com/t/jk6b2z
> refactor: remove subtitle from external link modal

- resources/assets/js/navbar.js
Adds x-data parameter to the navbar script so we can reuse the function on explorer and add the specific variables of that navbar
Related to https://github.com/ArkEcosystem/explorer.ark.io/pull/827
- …
> feat: add xdata parameter to navbar scripit

- resources/assets/css/_slider.css
- resources/views/includes/slider/scripts.blade.php
https://app.clickup.com/t/jk7j2n
- Removed the condition that was making the dots not clickable (notice that that condition probably was added for some reason but I was unable to find probably was no longer valid)
- Removed the margin between the dots mentioned on the ticket
To test merge this dependency to msq
-   [ ] I added an explanation on how to use the …
> fix: make slider dots always clickable

- resources/views/inputs/upload-image-collection.blade.php
> refactor: sorting image collection styling

- resources/views/navbar/profile.blade.php
Part of :
https://app.clickup.com/t/hk9fjp
Adds the possibility of defining custom attributes ( for example target="_blank") and a raw href for the items on the profile menu
To test see the msq PR:  https://github.com/ArkEcosystem/marketsquare.io/pull/2038
-   [ ] …
> feat: allow attributes and href on profile menu

- resources/views/navbar.blade.php
https://app.clickup.com/t/9bvx25
> refactor: ui use navbar aria label

- README.md
- resources/assets/js/slider.js
- resources/views/includes/slider/scripts.blade.php
https://app.clickup.com/t/hq4d7m
> refactor: slider move js & add keyboard events

- resources/views/navbar.blade.php
- resources/views/navbar/notifications.blade.php
Related to https://app.clickup.com/t/n17nv5
> refactor: hover tweaks for navbar notifications

- resources/assets/css/_slider.css
- resources/views/includes/slider/scripts.blade.php
- resources/views/slider.blade.php
- src/helpers.php
https://app.clickup.com/t/mz8bh4
Adds a new helper used to extract the breakpoints to be used on the sliders and used them to create a "grid" that ensures the elements have the proper width before Swiper is loaded. 
Merge this on msq and recompile assets, navigate all the sliders (home page, project gallery, etc) the slides should be shown with the proper `width`.
Notes:
1. For the sliders that have more than one row I am only showing the first row, once swiper is loaded it adds the rest of the rows. I made some experiments and its technically possible to create a grid for those scenarios but is very complex, think doesn't worth and that "jump" is not really annoying (from my point of view)
2. Of course the controls (navigation, etc) doesn't appear until the elements are loaded
Tip: is …
> chore: use grid classes for preventing jump on sliders

- resources/views/alert.blade.php
- resources/views/external-link-confirm.blade.php
https://cryptoarkproject.slack.com/archives/CLAGGC7LY/p1625085951329300
https://app.clickup.com/t/nbbywd
> fix: long external link

- resources/assets/css/_forms.css
https://app.clickup.com/t/nhefae
> feat: add class to hide number input arrow buttons

- resources/lang/en/forms.php
- resources/views/external-link-confirm.blade.php
- resources/views/inputs/checkbox.blade.php
Reverts ArkEcosystem/laravel-ui#504
> Revert "feat: allow to dismiss future modal alerts for external links"

- src/Rules/Concerns/ValidatesEmptyString.php
- src/Rules/IsNotEmpty.php
- src/Rules/MarkdownWithContent.php
Relates to https://app.clickup.com/t/nk8rpj
> refactor: empty string rule

- resources/assets/css/_buttons.css
https://app.clickup.com/t/nncghk
This PR changes the word breaks property on `.button-tag` css class.
It's related with https://github.com/ArkEcosystem/marketsquare.io/pull/2128.
Be sure to test it on MSQ. …
> fix: improve tag text wrapping

- resources/assets/js/user-tagger.js
- resources/views/inputs/user-tagger.blade.php
Mostly cosmetic changes. Relates to https://app.clickup.com/t/nk8rpj
Fixes a bug where, when adding a tag in the editor, clicking the link would scroll the page to the top
> refactor: update user tagger

- resources/views/navbar/content.blade.php
https://app.clickup.com/t/ntac95
> refactor: mobile navbar sign in remove mobile padding

- resources/assets/js/compress-image.js
https://app.clickup.com/t/nva4ac
> fix: Image won't upload if previously removed

- resources/assets/css/_general.css
- resources/views/navbar.blade.php
- resources/views/navbar/items/desktop.blade.php
https://app.clickup.com/t/nzd447
> refactor: navbar height & centering updates

- resources/views/status-circle-shallow.blade.php
https://app.clickup.com/t/dd4av1
Also updates the icon used to match the design
> refactor: status circle shallow tooltip

- resources/views/inputs/rich-select.blade.php
https://app.clickup.com/t/p18mwd
> refactor: rich select class property

- resources/views/metadata-tags.blade.php
https://app.clickup.com/t/10xk0pt
> refactor: add meta-description to metadata-tags component

- resources/assets/css/_alerts.css
https://app.clickup.com/t/ntfyv2
> fix: center the text in the alert on mobile

- resources/assets/css/_forms.css
- resources/views/inputs/switch.blade.php
Fix the `<x-ark-switch>` component that wasn't visible before (related to Nodem)
> fix: switch component

- composer.json
- composer.lock
Reverts ArkEcosystem/laravel-ui#525
> Revert "chore: upgrade dependencies"

- README.md
> chore: update modal usage in readme

- EXAMPLES.md
Fix component name in the documentation.
> fix: loader icon documentation

- src/UserInterfaceServiceProvider.php
> fix: add "loader icon" in the service container

- resources/views/details-box-mobile.blade.php
> refactor: align text and icon in mobile details box

- resources/views/modal.blade.php
https://app.clickup.com/t/qtbua4
The issue is because the `body-scroll-lock` plugin manually adds padding to the modal (trough  `style` attribute) that disappears after livewire makes a request and re-renders the content. (The padding is as a workaround to keep the scrollbar gap ([`reserveScrollBarGap` setting](https://github.com/willmcpo/body-scroll-lock#reservescrollbargap)).)
This PR adds a `wire:ignore.self` to ensure livewire doesn't override the modal wrapper. Since it uses the `.self` modifier it only prevents the wrapper to be modified but the modal content should work fine as always (as proof you can try to submit the modal  without adding any password and you will see that it adds the error label meaning it successfully re-rendered the content of the modal)
In other words, it …
> fix: prevent livewire from shifting modals when page has scrollbar

- resources/assets/css/_components.css
- resources/views/accordion.blade.php
- resources/views/dropdown.blade.php
- resources/views/status-circle-shallow.blade.php
- resources/views/tables/row.blade.php
- Accordion: changed js name/format & added some css classes for identifying - should be no change in UI or functionality
- Table Row: removed full height css class to fix accordion bug in tables (firefox) - should be no change in UI or functionality
- Dropdown: moved some default prop values & added on-close method. Also updated corner radius to match style guide - should be no change in functionality 
- Status Icon Component - update paused icon to use the correct svg
**Note: the table row change COULD be a breaking change if something relies on height-full. To remedy:**
```
<x-tables.row class="h-full" ...>
```
I tested the table row change on Nodem & Explorer with Chrome, Safari & Firefox but didn't notice any issues
-   [ ] I checked my UI changes against the design and there are no …
> refactor: various component updates

- resources/views/tables/row.blade.php
https://app.clickup.com/t/qtgwq4
Improves table row by adding an optional tooltip.
> feat: add tooltip to table row

- resources/views/external-link-confirm.blade.php
As the title says
https://app.clickup.com/t/yy957w
To test: merge this on msq and try to open an external link with the mouse scroll
> fix: handle opening external links when using mouse scroll click

- src/Mail/ContactFormSubmitted.php
Related to https://app.clickup.com/t/10htxz6
Adds a check for a support email address from the config, and falls back to the "stub" if it doesn't exist
> refactor: allow custom support email

- resources/views/footer-bar-desktop.blade.php
- resources/views/footer-bar-mobile.blade.php
- resources/views/footer-copyright.blade.php
- resources/views/footer-social.blade.php
- resources/views/footer.blade.php
Related to https://app.clickup.com/t/10htxyf
Adds the following new properties to the footer components: 
- `copyText` to allow overriding of the copyright text
- `socials` to allow overriding of the social links …
> refactor: footer copyright & social properties

- resources/views/pages/contact/content.blade.php
Related to https://app.clickup.com/t/118prnn
Accept a custom documentation URL  in the docs page
> refactor: accept documentation url on contact form

- resources/lang/en/general.php
- resources/views/footer-copyright.blade.php
- resources/views/simple-footer.blade.php
https://app.clickup.com/t/12b0th3
as title says
> fix: capitalize all rights reserved in footer

- resources/views/details-box-mobile.blade.php
Related to https://app.clickup.com/t/1e6u51q
> refactor: extra attributes for details-box-mobile component

- resources/assets/css/_buttons.css
- resources/views/tables/view-options.blade.php
https://app.clickup.com/t/12gvq22
Improve icon spacing on different states: normal, active, focus.
> refactor: improve view-options component

- resources/views/details-box-mobile.blade.php
> refactor: missing prop for details-box-mobile component

- resources/views/includes/slider/header.blade.php
- resources/views/tables/view-options.blade.php
https://app.clickup.com/t/rag8g9
Concern all `blade` files located within `views/includes` and `views/tables`  
> refactor: use conditional classes for table components

- resources/views/navbar/items/desktop.blade.php
- resources/views/navbar/link-mobile.blade.php
https://app.clickup.com/t/rag8g9
Concern all blade files located within views/navbar
> refactor: use conditional classes for navbar components

- resources/assets/css/_components.css
- resources/views/tabs/wrapper.blade.php
https://app.clickup.com/t/12pgp1d
This PR moves a class from css to the component itself for better handling width adjustments.
> refactor: move w-full to tablistClass for better customization options

- EXAMPLES.md
- resources/views/tabs/wrapper.blade.php
https://app.clickup.com/t/12w4kt0
This PR allows to better customize tabs component, in particular tab list.
This is useful on mobile or tablet where we want to show tab list in a different way like "select box" on mobile, "drop-down" on tablet and default tab list on desktop.
-   [x] I added an explanation on how to use the component to the readme _(if …
> refactor: improve tabs component customization

- resources/views/inputs/includes/input-error-tooltip.blade.php
- resources/views/inputs/includes/input-label.blade.php
- resources/views/inputs/includes/tile-selection-option.blade.php
https://app.clickup.com/t/rag8g9
Concern all blade files located within inputs/includes
> refactor: use conditional classes for input includes

- src/Http/Middlewares/DropInvalidLivewireRequests.php
- tests/Unit/Livewire/DropInvalidLivewireRequestsTest.php
https://app.clickup.com/t/1j88awg
> feat: drop invalid Livewire requests

- resources/views/local-time.blade.php
- src/Support/DateFormat.php
- src/UserInterfaceServiceProvider.php
Adds JS formats used by the time component
related to https://app.clickup.com/t/1je4j6r
> feat: add local time component

- src/Http/Livewire/Concerns/HasPagination.php
https://app.clickup.com/t/1jzanty
> fix: use setPage instead of assigning page variable
