- resources/views/clipboard.blade.php
There is a strange bug in the table of servers on the user home page, to reproduce you just need to change the list of servers for another server type or another token, in the screenshot above the select tab is "development" if I click on the "production" tab it throws
```
Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': '@click' is not a valid attribute name.
at morphAttrs (https://one-click.test/vendor/livewire/livewire.js?id=c1db26b321e994f87254:13:77001)
```
After spending a lot of time on this all points to be a conflict within livewire and  alpine (related issue https://github.com/livewire/livewire/issues/828)
After changing @change for `x-on:change` the problem is fixed
> fix: @click event in clipboard livewire conflict

- resources/views/inputs/rich-select.blade.php
- src/UserInterfaceServiceProvider.php
Rich select component based on the style guide:
Note: the only place this component is used is on the explorer advanced search (pending PR); there, it has a different button style. The screenshot is for the default styling
> feat: rich select component

- resources/assets/css/_tables.css
- resources/tailwind.config.js
Some of the CSS related to the hover/highlighting  for the table rows is being removed in production builds, this PR prevents that
> fix: ensure purgecss does not remove table hover related styles

- resources/views/inputs/rich-select.blade.php
The rich select has a hidden input  that carries the selected value, this value is assigned every time the select changes but was not being  assigned for initial values
That problem was causing a bug in the advanced search on explorer: https://app.clickup.com/t/aeyr55
Fixed here
> fix: ensure the initial value is added to the hidden input

- resources/views/inputs/input-with-icon.blade.php
- resources/views/inputs/input.blade.php
This will allow overwriting the default `wire:model` binding by passing `no-model` to the input and using whatever binding you want, e.g.:
```
<x-ark-input
type="text"
:name="foo"
no-model
wire:model.lazy="bar"
/>
```
> feat: allow setting custom models on inputs

- resources/assets/css/_components.css
- resources/views/navbar/notifications.blade.php
- Moved the `dropdown-button` class 
- Colors change for the notification icon within navbar
- Margin to recenter the notification icon
> refactor: navbar notification icon tweaks

- resources/views/details-box.blade.php
For a feature in the nodem repository related to show a progress circle, I need to use a custom icon component that requires me to override the default icon wrapper on the `resources/views/details-box.blade.php` component.
Related to: https://github.com/ArkEcosystem/nodem/pull/46
> feat: allow to override the icon wrapper

- resources/views/status-circle-shallow.blade.php
Use full class names on the status icon to make it work with purge css
> fix: use full classes names for purgecss

- resources/assets/css/_tables.css
- resources/views/tables/cell.blade.php
- resources/views/tables/row.blade.php
- Add necessary classes and styles to make the highlighted rows look ok on firefox
- The classes removed from the cells are also defined on the _tables.css file, so there are not necessary
- Tested on safari, chrome, and firefox
> fix: highlight on firefox issue

- resources/views/dropdown.blade.php
- resources/views/inputs/rich-select.blade.php
https://app.clickup.com/t/ayubjz
The ticket mentions only the server dropdown that comes from the dropdown component so the change will affect every dropdown we have but that is correct since the design and the style guide consider a shadow instead of the border as far as I can tell.
Same for the rich select component, it has a ring but in any of the designs, we have that border.
Tested on different projects and looks fine but there may be a dropdown hidden there that may be affected visually speaking, if that is the case I think that the hypothetically dropdown can be fixed individually
> feat: remove ring classes from dropdowns

- resources/lang/en/actions.php
- resources/views/slider.blade.php
Designs were showing a chevron with a right direction next to the `View all` within sliders. Also localized that action.
> refactor: added chevron next to view all within slider component

- resources/assets/js/rich-select.js
- resources/views/inputs/rich-select.blade.php
As we do with the modals and the pagination, moved the rich select scripts to a global file to avoid repeated and large code.
As always the next step once this is merged is to update all the project that uses the rich-select component
(already tested on nodem and explorer)
Test it here https://github.com/ArkEcosystem/explorer.ark.io/pull/678
> refactor: move rich select scripts to a global file

- resources/views/pagination-url.blade.php
- resources/views/pagination.blade.php
Fixes two different problems:
1. When using the form to put the page number manually, the request lost the rest of the query parameters. In other words, if you have, let's say, a search `page?search=2` and change the page with the form, the URL will be lost the `search` query param.
2. The `pagination-url` is using buttons instead of the link, so it's not working 
**Note:** All the projects have local views for the pagination so even if this is merged it will not solve the issue until we update those files, however, only the ones that use pagination-url or `get` parameters on the paginated page should be affected. I will wait until this is merged to update the rest of the projects.
> fix: use links in pagination url and fix form parameters

- resources/views/pagination-url.blade.php
- resources/views/pagination.blade.php
- src/UI.php
Two problems:
1. Some test is failing because the pagination used all the request parameters to fill the hidden input, that was wrong we should only use the GET params
2. The pagination form doesn't handle well the nested parameters like `&type[state]=something`, also fixed
> fix: the parameters for the pagination should come only from the query

- resources/views/pagination-url.blade.php
- resources/views/pagination.blade.php
- src/UI.php
Encounter an issue when the users try to change the pagination page with the form. The issue is that the form `action` comes from the pagination data that in livewire points to a livewire route and not the current route.
To replicate:
1. Change the page with the page buttons
2. Once updated, try to change the page with the form.
That path was never really necessary, and just remove it solves the problem since the default form action is the current page.
> fix: remove path that has conflicts with livewire

- resources/views/pages/contact/content.blade.php
- src/Http/Controllers/ContactController.php
1. Since the contact form controller returns the contact view if I refresh the page it re-submit the form data and it sends the email again so I change to use a redirect instead.
2. Plus, after a contact form submission the user scroll is at the top of the page so unless the user scrolls down and looks for the success message it can be easily lost. Added an anchor to send the user to the contact form again after submission.
> fix: prevent contact form re-submission

- resources/views/inputs/upload-image.blade.php
- src/Components/UploadImage.php
The upload image component now has a readonly prop that hides everything related to replace/remove the current photo
> feat: readonly option for image upload

- resources/views/navbar.blade.php
In order to add the search icon that is in the new search design, I need a new slot on the navbar
> feat: slot to add content in the middle of the navbar

- src/Casts/Markdown.php
https://app.clickup.com/t/crz75r
The markdown extension doesn't really filter the HTML attributes that is being done in a custom Markdown caster. This PR adds the `<ins>` tag as an allowed attribute while keeping the same security filters.
Build the code in a way we can add more allowed tags in the future.
> feat: accept `ins` tag on the markdown caster

- resources/views/slider.blade.php
UI tweaks solving a couple issues I encountered. 
- Allow to hide the `View All`
- Truncation of the slider's title, that one is mostly for the small resolutions where the name was overlapping with the bullets (might change that to be optional maybe ?)
- Padding adjustments, the "View All" and the slider's title weren't properly aligned before that.
> refactor: slider slide tweaks

- resources/assets/js/tippy.js
Removes the click trigger on the tooltip that is keeping the tooltip over the screen until I click somewhere else
On mobile devices, it still shows the tooltip until I click somewhere else but personally don't felt that it's so annoying as the desktop version since is a common gesture but I let that open to your better opinion.
The alternative for mobile is to use the `touch` property that shows the tooltip while the user holds the tooltip trigger but if that is the case we actually have a `[data-tippy-hover]` (instead of `[data-tippy-content]`) attribute that already add that behavior so we can just replace the data attributes where we can that behavior or keep that as default
Just my two cents here: I tested the tooltips with the hold option on my cellphone and I didn't know I needed to …
> chore: tooltip remove click trigger

- resources/views/navbar/items/mobile.blade.php
https://app.clickup.com/t/kmx4nk
added the `x-cloak` attribute so the mobile menu is not shown until the scripts are loaded, which prevents a jump from happening on the mobile version of the site
> chore: dont show the mobile until menu scripts loaded

- resources/views/navbar.blade.php
- resources/views/navbar/items/desktop.blade.php
Adds a negative margin to the button to compensate the navbar padding, since they have a border below that add some space below still looks centered
> chore: navbar button border alignment

- resources/assets/css/_tables.css
- resources/views/tables/cell.blade.php
https://app.clickup.com/t/d72r99
Suddenly the hover effect on the tables is broken, I went over the history, and doesn't seem to be related to something we made but maybe some update in the browsers (webkit etc), for example in Firefox the custom attribute we had for the box-sizing that used to fix the padding is no longer working.
This PR adds a new div in the cell to be used as the background and with some CSS :magic: its now cross-browser again, good news no longer need `-moz-prefix` or stuff like that
This is how it looked:
> fix: table hover effect is no longer working

- resources/views/slider.blade.php
Adds an option to add some padding to the slider wrappers to prevent an issue with shadows being cut because the overflow
> chore: option for add spacing to the slider to prevent shadow overflowing

- resources/views/icon.blade.php
- resources/views/pages/contact/content.blade.php
- resources/views/social-square.blade.php
The social icons on the contact page now accept a custom hover class so we can change the color of the hover effect when reusing the contact component.
This PR also changes the @svg component for <ark-icon and make it possible to pass a custom size (by sending a size string that is not part of the list)
> chore: make contact page social icons configurable

- resources/assets/css/_components.css
- resources/views/modal.blade.php
Makes modals take full width on smaller screens. If you did not use the modals properly regarding widths (in other words you didn't set it through the `widthClass` property) you need to update the modals to use that one
> refactor: make modals full screen on md screens and smaller

- resources/assets/css/_forms.css
- resources/views/inputs/tags.blade.php
Currently, that class is only on the scripts so purgecss is removing it
Plus: the tags prop doesn't need to be required
> chore: ensure tags focus class is not purged

- resources/assets/js/markdown-editor/css/style.css
- resources/views/inputs/markdown.blade.php
- src/Support/MarkdownParser.php
- Removes all the tags that are not part of the basic wyswyg editor
- For the header it first encodes the `#` symbol so if the user tries to write a header will see exactly what it write
- In the case of the editor the best workaround I found is to disable the style of the headers when the toolbar is `basic`
> feat: markdown parser for fields edited with the basic wyswyg editor

- resources/views/expandable.blade.php
Add a `showMore` slot on the component, which is useful for situations where we don't want to expand/collapse the button when clicking on it.
> refactor: added showMore slot for the expandable component

- resources/assets/js/tippy.js
Uses the `message.processed` event  to detect changes on the livewire component and activate the new tooltips that can potentially appear
> feat: initialize tooltips when a livewire component is updated

- resources/assets/css/_buttons.css
Since tags are widely used, I thought was great having a css class to style them around the entire ecosystem.
I've also added the outline version.
| Button | Normal state | Hover state | Disabled state |
|---|---|---|---|
| .button-tag | x | x | x |
| .button-outline | x | x | x |
| .button-tag-outline | x | x | x |
| .dark .button-tag | x | x | x |
| .dark .button-outline | x | x | x |
| .dark .button-tag-outline | x | x | x |
-   [ ] I regenerated the `icons.html` file …
> feat: add button-tag css class

- resources/views/js-modal.blade.php
Changes the classes for the js-modal to prevent scrolling when the modal is on the footer of the page (before </body>) like it works here https://github.com/ArkEcosystem/marketsquare.io/pull/1418
Currently, when the modal is opened, the page is scrolling to the bottom of the page. This PR solves that
-   [x] I added an explanation on how to use the component …
> fix: js-modal fixed position to prevent autoscrolling

- resources/views/inputs/upload-image-collection.blade.php
- resources/views/inputs/upload-image-single.blade.php
https://app.clickup.com/t/f3434j
The delete button of both components for uploading image has a wire:key with the same name, that is causing issues if both components are added on the same page like is described on the ticket.
To test use this version of the package on msq and try to follow the step described on the ticket:
1. Create a project
2. Add a Project Logo
3. Add a screenshot image
4. Save project
5. Edit Project
6. Try to Remove Project Logo image
7. Fails
Once this is merged the problem should be solved.
-   [] I provided a screenshot of my …
> fix: make wire:key of the delete button unique

- resources/assets/css/_components.css
Because class for disabling the pointer-events on disabled titles the tooltips applied to those are not working, this PR solves the problem while keeping the same disabled behaviour.
-   [ ] Ready to …
> refactor: keep pointer events on disabled tiles

- resources/views/inputs/rich-select.blade.php
This is causing a JS error when using the rich select with a name prop
> fix: rich select is using the name variable incorrectly

- resources/lang/en/forms.php
- resources/views/inputs/upload-image-collection.blade.php
- src/Components/UploadImageCollection.php
- Prevent that the user upload more images than the limit (currently can bypass the limit if upload multiple ones at once)
- The max qty of images is now inside a method in the trait that can be overridden in case we need a different limit,
- By default, the component will not have limit
Once merged upgrade this library on msq and try to upload more than 8 images at once, you should see a warning
-   [ ] I regenerated the `icons.html` file and checked if my newly added …
> fix: dont allow more images than the limit / make the limit overridable

- resources/assets/js/tags.js
New `selectedTagRemoved` event listener allowing us to remove a temporary tag from the `taggle` input on it's deletion.
> feat: event listener to remove temporary tag from input

- resources/assets/js/user-tagger.js
The user tagger is currently not initializing the initial value of the `wire:model` so when editing a value it doesn't works, this pR fixed the problem
> fix: set the initial value of the user tagger

- resources/views/inputs/includes/tile-selection-option.blade.php
https://app.clickup.com/t/fq7327
> fix: remove vertical space on mobile for tile selection component

- resources/views/inputs/includes/tile-selection-option.blade.php
https://app.clickup.com/t/g32f3z
Due to the async way livewire works the tile selection related to the platform selection when registering a project are not disabled until the model is saved so if the user clicks past it can select more options.
This PR disabled the files while making the request to prevent that
To test create a new project and try to select more that 5 platforms 
-   [] I regenerated the `icons.html` file and checked if my newly added icon is shown …
> fix: disable tile selection while making requests

- resources/views/secondary-menu.blade.php
Related to fixes for this ticket: https://app.clickup.com/t/g33fcj
Dependant on https://github.com/ArkEcosystem/laravel-hermes/pull/28
Due to a change in the styles for the notifications, dropdown is possible that the notifications dropdown grows over the screen with a large title, this PR prevents that
Test by following the instructions on the main PR https://github.com/ArkEcosystem/laravel-hermes/pull/28
-   [ ] I regenerated the `icons.html` file and checked if my …
> fix: prevent the notification dropdown to be larger than screens

- src/Rules/MarkdownMaxChars.php
- tests/Rules/MarkdownMaxCharsTest.php
The max chars rule for markdown is incorrectly counting the number of character when using unicode text like the one used on the ticket, this PR fixes that and adds a regression test.
To test merge this on msq and paste the text from the ticket.
-   [x] Documentation …
> fix: use mb_strlen to correctly count unicode chars

- resources/views/inputs/includes/tile-selection-option.blade.php
https://app.clickup.com/t/g523f8
As explained on the ticket currently the "view more" button is not working on mobile for showing the hidden tiles.
Testing by opening the create registration form on mobile and using the view more button
-   [ ] Documentation _(if …
> fix: broken mobile hidden behaviour on tiles

- resources/views/inputs/includes/tile-selection-option.blade.php
- resources/views/inputs/tile-selection.blade.php
- Removes the alpine x-model from the tile-selection that was having issues related to syncing values between the wire:model and the x-model
- Removes the select all that is currently not used, if is used in the future we can re-implement it following a different approach since the current one was not syncing the wire:model also
-   [ ] I added an explanation …
> fix: remove selection tiles select all and use only wire:model

- resources/views/inputs/user-tagger.blade.php
https://app.clickup.com/t/g77wua
Adds a `word-break` style to the user tagger component to prevent it from growing with larger words like the one on the video.
To test add a review and fill it with a large word without spaces like `aaaaaaaaaa......etc....etc` if the world is large enough it should break the word on the next line.
Note: you may ask why I am not using the `break-words` class and its because it simply didn't work, that class adds the `overflow-wrap: break-word;` instead of `word-break: break-word` and it doesn't work.
Another option was to create a CSS style for this field but figure out that this field already has inline styles and will be better just to add another style instead of growing the CSS stylesheet.
-   [x] I checked my UI changes against the design and there are …
> fix: break works on user tagger to prevent horizontal growing

- EXAMPLES.md
- resources/views/dropdown.blade.php
Add a new option to the `dropdown` component allowing us to apply a `tippy-tooltip` on the dropdown's button.
> refactor: tooltip option for dropdown component

- src/Rules/MarkdownMaxChars.php
- tests/Rules/MarkdownMaxCharsTest.php
https://app.clickup.com/t/gd0exq
To fix the characters count I am updating the rule for max chars on markdown text to ignore whitespace resulted from the text conversion.
To test create a review and first add exactly `1001` chars => you should see a validation error
Then try with exactly 1000 chars  => it should pass the validation
-   [x] I added an …
> fix: trim markdown text before counting

- resources/views/inputs/includes/input-error-tooltip.blade.php
https://app.clickup.com/t/g97pmg
When you change from one error to another in an input is not updating the error message properly
To test follow the steps on the ticket the problem should be fixed now
-   [X] I provided a screenshot of my changes to the component _(if applicable)_
-   [] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
- …
> fix: add unique wire:key error tooltip to prevent overlapping

- resources/views/modal.blade.php
New option for modals with "fixed" position
When set, the modal will be not centered vertical but will be shown on the top of the page (with a margin) this will fix a jump that happens when the modal content change (like the modal for editing a project tag that changes his size within the autocomplete)
For test instructions and screenshots see the related ticket on msq: https://github.com/ArkEcosystem/marketsquare.io/pull/1641
-   [x] I checked my UI changes against the design, and there are no notable differences
-   [x] I checked my (code) changes for obvious issues, debug statements, and commented code
-   [ ] I regenerated the `icons.html` file …
> feat: add option for modals with a fixed position

- resources/assets/js/tippy.js
In some case we may need to trigger the tippy function after the page is initialized because the element was added later, a specific use case is the hubs tooltips on the dropdown menu 
-   [ ] Ready to …
> feat: make tippy globally available

- resources/assets/js/tags.js
https://app.clickup.com/t/r995tu
The tags component script has a `allowedTags` options that expect an array of the tags that can be used, (currently used on project registration > "add platform") since in a recent PR  the case preservation was disabled the script is currently creating a loop in the process of picking an element to the list that have some elements with uppercase letters.
This PR updates the `preserveCase` to be enabled if we have a list of valid options.
- …
> fix: infinite loop in tag component when mismatching case

- resources/views/inputs/includes/tile-selection-option.blade.php
- resources/views/inputs/tile-selection.blade.php
https://app.clickup.com/t/gb2thc
The x-model that was being used on the tile component was causing a re-render on the tiles that will resetting the show more button, refactored to fix the problem
To test add this to msq and try to replicate the issues from the ticket.
- …
> fix: remove conflicting alpine x-model on tiles component

- resources/views/no-results.blade.php
Related to this ticket https://app.clickup.com/t/gf2kvf
Adds a way to override the no-results image for msq
> feat: allow to change the no-results image

- resources/assets/css/_tables.css
Related to https://app.clickup.com/t/qk5yjc
Used here https://github.com/ArkEcosystem/marketsquare.io/pull/1732
If we add a `tabindex` to a row it means it can be focused using tab navigation, in that case, I am applying the same styles used when hovering the mouse:
- …
> feat: add table row focus classes

- resources/views/external-link-confirm.blade.php
- src/UserInterfaceServiceProvider.php
Needed for using on the fortify package (see https://github.com/ArkEcosystem/laravel-fortify/pull/124)
-   [] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
> feat: move external link with confirmation modal to the ui library

- resources/assets/js/tippy.js
https://app.clickup.com/t/gv1bvu
as the title says
Test by triggering a tooltip on mobile, it should disappear when you scroll the page
-   [] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [x ] I added an explanation on how to use the component to the readme _(if necessary)_
> feat: hide tooltips on scrolling

- resources/views/livewire/toast.blade.php
https://app.clickup.com/t/g98vmk
Added `wire:key` attribute to the toasts to fix the issue described on the ticket.
To test just follow the steps on the ticket
-   [] I added an explanation on how to use the component to the readme _(if necessary)_
> fix: add wire:key to prevent livewire issues on toast notifications

- resources/assets/js/markdown-editor/markdown-editor.js
Add an `onFocus` and `onBlur` methods on the markdown editor scripts, those are meant to be overridden in case we want to add some behaviour.
Use case: validate the project description until blur (on this PR https://github.com/ArkEcosystem/marketsquare.io/pull/1793)
-   [] I added an explanation on how to use the component to the readme _(if necessary)_
-   [ …
> fix: add overridable blur & focus events to the markdown editor

- resources/assets/css/_forms.css
https://app.clickup.com/t/hb8e0v
> fix: disable tag input when 5 platforms are selected

- resources/assets/css/_forms.css
https://app.clickup.com/t/hd8fvd
Truncates the tags when are longer than the available space 
To test just update this dependency on msq and add a long tag (30 chars) in a small screen 
-   [ ] Ready …
> fix: truncate long tags in tag component

- resources/assets/css/_forms.css
This will fix a small issue on Tag input (on small viewport or on small modal window), that hide the caret and the input text (see video below).
https://user-images.githubusercontent.com/2118799/115403135-6e4fa800-a1ec-11eb-8c06-8027c6347f55.mov
-   [ ] Documentation …
> fix: tag input on small screen

- resources/views/errors/404.blade.php
https://app.clickup.com/t/jk8452
The error described on the ticket is related to the published 404 page is trying to use a local breadcrumb component, this PR updates it to use the ui component instead
In case you are wondering that breadcrumb is the correct one, is even the one being used on the explorer 
-   [ ] I added an explanation on how to use the …
> fix: use ui breadcrumb on 404 page

- resources/assets/css/_general.css
- resources/views/navbar.blade.php
- resources/views/slider.blade.php
> fix: revert slider padding changes and move navbar-container to class

- resources/views/navbar.blade.php
https://app.clickup.com/t/jq8eh5
This will fix the navbar border bottom on every viewport size and even when we open the dropdown with a page scrolled (since we hide the border when the page starts to be scrolled).
-   [ ] Tests …
> fix: navbar border

- resources/assets/css/_tables.css
According to the design, the space between the rows should `24px` be and not `16px` as its currently is, related to this PR https://github.com/ArkEcosystem/explorer.ark.io/pull/730
Before:
After:
-   [ …
> fix: proper spacing in responsive "table" rows

- resources/assets/js/modal.js
Related to https://app.clickup.com/t/x1hed4
The script for the modal now gets the element that will be scrollable (while the rest of the page is locked) from a method so we can potentially override it.
Use case: explorer search modal, see explorer PR: https://github.com/ArkEcosystem/explorer.ark.io/pull/778/files
-   [ ] I added an explanation on how to use …
> feat: get the scrollable element to lock from an overridable method

- resources/assets/css/_forms.css
- resources/tailwind.config.js
- resources/views/inputs/toggle.blade.php
https://app.clickup.com/t/kkbc0k
Updates the toggle component according to the style guide including the focus state.
To test:
1. merge this on explorer,
2. recompile assets,
3. Try to navigate the settings dropdown with the keyboard, the toggle should have the same design as the style guide,  should be animated, and should have the ring for the focus state
-   [x I checked my UI changes against the design and there are no notable differences
- …
> refactor: update toggle component design to match style guide

- resources/views/inputs/upload-image-single.blade.php
> fix: revert cropping wire:model and add button type to avoid page refresh

- resources/views/info.blade.php
> fix: large info icon styling

- resources/views/inputs/upload-image-single.blade.php
https://app.clickup.com/t/mbccap
Disables the delete button while deleting to prevent double click
To test just merge this to msq and try to replicate the issue
> fix: disable profile photo delete button while busy

- resources/tailwind.config.js
Related to https://app.clickup.com/t/mb5pj7 and https://github.com/ArkEcosystem/explorer.ark.io/pull/835
Add a new lg shadow with less opacity for the search module on explorer
-   [ ] Ready to be …
> feat: lg shadow with less opacity

- resources/views/inputs/upload-image-collection.blade.php
Add `cursor-pointer` on image collection only when sorting feature is enabled.
> chore: add `cursor-pointer` to sortable images

- resources/assets/js/navbar.js
Adds a new parameter to whether or not to use the dark border and shadow on the navbar when using the scrolling behavior.
Related to: https://app.clickup.com/t/mkcymq https://github.com/ArkEcosystem/explorer.ark.io/pull/848
-   [ ] …
> fix: handle dark theme on navbar border and shadow

- EXAMPLES.md
- README.md
- resources/views/inputs/includes/input-label.blade.php
- resources/views/inputs/input.blade.php
Allow us to pass a custom tooltip, for example : 
```html
<x-ark-input>
<x-slot name="customTooltip">
<x-ark-info tooltip="hello" type="info" />
</x-slot>
</x-ark-input>
```
> refactor: make use of ark-info component for the tooltip of input-label 

- EXAMPLES.md
- config/ui.php
- resources/views/inputs/upload-image-collection.blade.php
- resources/views/inputs/upload-image-single.blade.php
https://app.clickup.com/t/mx7m44
This PR prevents users from uploading "bitmap" images.
It modifies `upload-image-single` and `upload-image-collection` components.
It also makes mime-types configurable for easy access in the future.
-   [x] Documentation _(if necessary)_ …
> refactor: remove bitmap support

- README.md
- resources/assets/js/markdown-editor/markdown-editor.js
- resources/views/pages/includes/markdown-scripts.blade.php
https://app.clickup.com/t/n979q9
Changes the markdown script to import the toastui-related scripts locally to avoid cdns 
After merged check:
1. https://github.com/ArkEcosystem/ark.io/pull/963
2. https://github.com/ArkEcosystem/marketsquare.io/pull/2090
-   [x] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_
-   [ ] …
> chore: include toastui editor scripts locally

- resources/views/inputs/markdown.blade.php
https://app.clickup.com/t/z9epbf
https://sentry.io/organizations/ark-ecosystem/issues/2392277890/events/30f7edb06b7049aba350936fcba37af0/?project=5387309
I was unable to reproduce the exception. However, I strongly believe the change I am submitting will fix the potential errors:
Explanation: the markdown component uses JS to update the value of a text `<input  />` added outside the markdown component while the user types. That input is used to emulate the `wire:model` behavior.
As you can see in the video below, the value is added to the `value` attribute every time you update the markdown content. The problem is that it is creating a lot of content with JS, which is potentially the reason for the corrupt view exception. 
I changed the input for a `textarea` that doesn't add any `value` …
> fix: livewire corrupt payload excepton when using markdown

- resources/views/includes/slider/scripts.blade.php
- resources/views/slider.blade.php
- src/helpers.php
Related to:
https://app.clickup.com/t/44rfxb
<strike>Currently, the ark website is broken (develop branch) because the slider view doesn't handle `null` breakpoints</strike>
The ark website will be broken once we update the UI dependency because the slider component doesn't handle `null` breakpoints.
While working on the fix figure out that the current solution for handling the breakpoints (that uses regex to parse the JS breakpoints) is not ideal since is easy to get the breakpoints as an array and then convert it to JS on the scripts view.
That also makes it easy to solve the issue on the ticket that was related to the default breakpoints and plus adds the grid classes that prevent any `jump` on the sliders that currently is not applied to sliders without custom breakpoints.
To test …
> refactor: use php arrays for define the slider breakpoints

- resources/assets/js/markdown-editor/markdown-editor.js
https://app.clickup.com/t/nqczb0
This PR improves Markdown Editor to force https prefix when filling in urls.
> refactor: force https prefix when using urls

- src/Components/UploadImageCollection.php
https://app.clickup.com/t/nz89ez
fix an issue that was causing the sorting is not to be applied when creating a project.
To test merge this on msq and try to sort the gallery images when **creating** a new project …
> fix: gallery sorting when creating a project

- EXAMPLES.md
- resources/views/includes/slider/scripts.blade.php
https://app.clickup.com/t/p18gyk
This requires `window.sliders['slider-id'].init()` to be called elsewhere. E.g. for Alpine:
```js	
$nextTick(() => { window.sliders['slider-id'].init() });
```
-   [x] …
> refactor: slider delay init property

- resources/assets/js/reposition-dropdown.js
https://app.clickup.com/t/nzempw
If the event has already been triggered, it won't trigger again when declared. This checks for that scenario and runs instantly if needed
> refactor: reposition dropdowns without event

- resources/assets/css/_forms.css
https://app.clickup.com/t/p9cnfc
Hides the icon for revealing the password that appears on Microsoft Edge based browsers.
To test merge this on any project like msq, recompile assets, and test any password input in an edge browser.
Note: if you use mac you can download a native version of the Edge browser for Mac
-   [ ] I added an explanation on how to use …
> fix: hide Edge's native password reveal icon

- resources/assets/css/_components.css
- resources/views/inputs/rich-select.blade.php
- resources/views/js-modal.blade.php
- resources/views/modal.blade.php
Related to https://app.clickup.com/t/nn835y
1. Renames the className used for custom scrollbars for something more general that we can reuse
2. Applies the custom scrollbar to rich select component (the problematic one in the ticket)
3. Since the old class is used on ark.io site and msq we need to update also those projects once this is merged:
a) https://github.com/ArkEcosystem/explorer.ark.io/pull/879
b) https://github.com/ArkEcosystem/marketsquare.io/pull/2174
c) https://github.com/ArkEcosystem/ark.io/pull/976
-   [x] I provided a screenshot of my …
> refactor: scrollbar design on windows

- resources/views/inputs/password-toggle.blade.php
https://app.clickup.com/t/p5fgqb
Most line changes are just spreading out the properties to improve readability.
Added a property to mark the field as masked which uses styling to hide the characters for a "text" input field.
To test:
- with nodem, checkout https://github.com/ArkEcosystem/nodem/pull/115
- update fortify in composer.json to pull `dev-refactor/disable-2fa-modal as ...`
- update ui in composer.json to pull `dev-refactor/password-toggle-masked-option as ...`
- sign in/up pages should have a password field with `type="password"`
- login, go to http://nodem.test/user/settings/security
- enable 2fa
- click to open recovery codes modal
- password field should have `type="text"` but still hide the characters
- toggling show/hide password should also work
-   [ ] I checked my UI …
> refactor: password toggle masked option

- resources/assets/css/_forms.css
- resources/views/external-link-confirm.blade.php
https://app.clickup.com/t/pb9v24
Updates the external link component for using the proper space
> fix: external link proper spacing

- resources/views/tables/view-options.blade.php
Related to https://app.clickup.com/t/pnac4g
Updates the View Options component to allow the changing of default colours. Nodem has a different colour scheme so this needs to allow different colours here: …
> refactor: view options component colour overrides

- resources/assets/css/_tables.css
Currently, when you focus on a row it has a blue border that looks weird
The only use case I am aware is the search results modal, you can test it by:
1. opening marketquare search modal
2. Search for something that has more than 1 result 
3. Click `down` key to navigate the results, you will see the fix whether or not this patch was added
-   [ ] I added an …
> fix: table row with focus style

- resources/views/inputs/switch.blade.php
Related to https://app.clickup.com/t/pxbnfu
This PR brings back the "Switch" component natural behavior.
We assume that the right position is the active value and the left position is the inactive. 
The corresponding label has to be highlighted and follow the toggle (left label highlighted when the toggle is on the left and vice-versa).
-   [ ] I added an …
> fix: "switch" component logic

- EXAMPLES.md
- resources/views/loader-icon.blade.php
This PR adds a loader icon, useful to use it inside a button.
**! Update !**
Found that we have already a [spinner loading icon](https://github.com/ArkEcosystem/laravel-ui/blob/master/resources/views/spinner-icon.blade.php#L10) but it uses `animateTransform` and it's [not fully compatible](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateTransform#browser_compatibility) yet.
-   [ ] I regenerated the `icons.html` file and checked if my newly added icon is …
> feat: add "loader icon"

- resources/views/loader-icon.blade.php
This PR allows to pass all attributes to the SVG that have been passed to the component. Some attributes are left out that make no sense to update (SVG's viewbox). Makes it easer to pass stuff like `<x-ark-loader-icon wire:loading.remove />`
-   [ ] Documentation _(if …
> refactor: pass all attributes to the loader component

- resources/views/external-link-confirm.blade.php
> fix: use exclamation-mark for external link icon

- EXAMPLES.md
- resources/views/dropdown.blade.php
- resources/views/tables/view-options.blade.php
https://app.clickup.com/t/pnabvn
This PRs adds `disabled` state for "table view-options" and "dropdown".
-   [x] Documentation _(if necessary)_
> feat: add disabled state for dropdown and table view options

- resources/assets/css/_document.css
On [this PR](https://github.com/ArkEcosystem/laravel-ui/pull/610) I removed the bottom margin for the nested unordered list but I missed the ordered list 
This PR removes the margin there too.
-   [ ] …
> fix: remove bottom margin for nested ordered list

- resources/views/modal.blade.php
If you wrap a modal in the form tag, the close (X) button will be made a submit button, since HTML automatically sets `type="submit"` to a button element if wrapped in a form ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type)), if no type is explicitly set. This PR makes the button of a "button" type, which prevents that.
I don't see this breaking anything because a modal's close button is never used to submit a form.
Let me know if it's necessary to create a ClickUp card for this.
-   [ ] I provided a screenshot of my …
> refactor: make modal's close button not a submit button

- resources/views/inputs/includes/input-error-tooltip.blade.php
Error tooltip is only shown in input fields on failed validation. Since you could potentially have the same validation error for multiple fields (for example: "This field is required."), this would produce a bug because two elements would have the same `wire:key` which is a collision (because `wire:key` is generated as the md5 hash of the validation message). This can be prevented by generating hash of the ID as well as the error.
-   [ ] I regenerated the `icons.html` …
> refactor: add ID to livewire key hash for input error tooltip

- resources/views/inputs/checkbox.blade.php
Since we have a few checkboxes whose label color needs to be overriden, this PR pulls the default text color class one element up. That way, the text color can still be overriden and it's defaulted to secondary-700.
-   [ ] Tests …
> refactor: allow checkbox text color to be overridden

- resources/views/tables/view-options.blade.php
https://app.clickup.com/t/1cryrgr
When a button is used inside a Livewire component and the `@click` attribute is toggled between rendering can cause issue with Livewire. In this case toggling between `@click` and `disabled` causing a `DOMException` in livewire.js.
-   [ …
> fix: keep table view option button click attribute in DOM

- resources/views/navbar/content.blade.php
https://app.clickup.com/t/z431xz
Prevents text wrapping on the log in button and updates the margin to give it more space on 360px screens
Dependant of https://github.com/ArkEcosystem/marketsquare.io/pull/2226
-   [X] I provided a screenshot of my changes to the component _(if applicable)_
-   [x] I regenerated the `icons.html` file and checked if my newly added icon is shown correctly _(if necessary)_ …
> refactor: prevent log in button wrapping on mobile

- resources/views/navbar.blade.php
Related to https://app.clickup.com/t/10ht8vj
Property to hide the separator between navigation links and the "content" after it
> refactor: navbar hide separator property

- resources/views/footer-copyright.blade.php
If there was no copyright slot and the ark product text wasn't being shown, an empty flex container was being output which caused additional padding
> refactor: footer copyright spacing tweak

- resources/assets/js/tippy.js
- resources/views/local-time.blade.php
Tooltips for the local time were only being shown after the second livewire load due to `initTippy` being called prior to alpine updating the tooltip content. This now handles initiating tippy on init
Relates to https://github.com/ArkEcosystem/explorer/pull/930
-   [ ] …
> refactor: tweak local time component tooltip
